name: Build UnityExplorer

# Controls when the action will run.
on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '-noci')"

    steps:
      # Setup

      - name: Checkout latest
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore

      #  Upload artifacts
      - name: Upload BepInEx6.IL2CPP
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx6.IL2CPP
          path: ./bin/Release/UnityExplorer.BepInEx6.IL2CPP/
          if-no-files-found: 'error'

      - name: Upload BepInEx5.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx5.Mono
          path: ./bin/Release/UnityExplorer.BepInEx5.Mono/
          if-no-files-found: 'error'

      - name: Upload BepInEx5.MonoBleedingEdge
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx5.MonoBleedingEdge
          path: ./bin/Release/UnityExplorer.BepInEx5.MonoBleedingEdge/
          if-no-files-found: 'error'

      - name: Upload BepInEx6.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx6.Mono
          path: ./bin/Release/UnityExplorer.BepInEx6.Mono/
          if-no-files-found: 'error'

      - name: Upload BepInEx6.MonoBleedingEdge
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.BepInEx6.MonoBleedingEdge
          path: ./bin/Release/UnityExplorer.BepInEx6.MonoBleedingEdge/
          if-no-files-found: 'error'

      - name: Upload MelonLoader.IL2CPP
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.MelonLoader.IL2CPP
          path: ./bin/Release/UnityExplorer.MelonLoader.IL2CPP/
          if-no-files-found: 'error'

      - name: Upload MelonLoader.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.MelonLoader.Mono
          path: ./bin/Release/UnityExplorer.MelonLoader.Mono/
          if-no-files-found: 'error'

      - name: Upload MelonLoader.MonoBleedingEdge
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.MelonLoader.MonoBleedingEdge
          path: ./bin/Release/UnityExplorer.MelonLoader.MonoBleedingEdge/
          if-no-files-found: 'error'

      - name: Upload Standalone.IL2CPP
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Standalone.IL2CPP
          path: ./bin/Release/UnityExplorer.Standalone.IL2CPP/
          if-no-files-found: 'error'

      - name: Upload Standalone.Mono
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Standalone.Mono
          path: ./bin/Release/UnityExplorer.Standalone.Mono/
          if-no-files-found: 'error'

      - name: Upload Standalone.MonoBleedingEdge
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Standalone.MonoBleedingEdge
          path: ./bin/Release/UnityExplorer.Standalone.MonoBleedingEdge/
          if-no-files-found: 'error'

      - name: Upload Editor
        uses: actions/upload-artifact@v4
        with:
          name: UnityExplorer.Editor
          path: ./UnityEditorPackage/
          if-no-files-found: 'error'
